version: '3'
services:
  selenoid:
    container_name: selenoid
    network_mode: bridge
    image: "aerokube/selenoid:latest-release"
    volumes:
      - ./config:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/video:/opt/selenoid/video
      - ./config/logs:/opt/selenoid/logs
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-service-startup-timeout","3m"]
    ports:
      - "4444:4444"

  selenoid-ui:
    container_name: selenoid-ui
    image: "aerokube/selenoid-ui:latest-release"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444",]
