version: '3'
services:
  selenoid:
    image: "aerokube/selenoid:latest"
    container_name: selenoid
    ports:
      - "4445:4444"
    networks:
      - selenoid
    volumes:
      - "$PWD/config:/etc/selenoid"
      - "$PWD/config/logs:/output"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/config/video:/opt/selenoid/video"
    environment:
      - "OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/config/video"
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-container-network", "selenoid", "-service-startup-timeout","2m"]

  selenoid-ui:
    image: "aerokube/selenoid-ui:latest"
    container_name: selenoid-ui
    links:
      - selenoid
    ports:
      - "8083:8080"
    networks:
      - selenoid
    command: ["--selenoid-uri", "http://selenoid:4444"]
  chrome_91.0.b:
    image: "dumbdumbych/selenium_vnc_chrome_arm64:91.0.b"
    container_name: chrome_91.0.b
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - selenoid
    volumes:
      - "/dev/shm:/dev/shm"
networks:
  selenoid:
    external:
      name: selenoid